"""create regions and citizen requests

Revision ID: a4d43ce37103
Revises: 
Create Date: 2026-09-18 00:19:50.709048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d43ce37103'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('parent_region_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_code'), 'regions', ['code'], unique=True)
    op.create_index(op.f('ix_regions_country_code'), 'regions', ['country_code'], unique=False)
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_table('citizen_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anonymous_reference', sa.String(length=100), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('issue', sa.String(length=150), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_requests_anonymous_reference'), 'citizen_requests', ['anonymous_reference'], unique=False)
    op.create_index(op.f('ix_citizen_requests_category'), 'citizen_requests', ['category'], unique=False)
    op.create_index(op.f('ix_citizen_requests_created_at'), 'citizen_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_citizen_requests_id'), 'citizen_requests', ['id'], unique=False)
    op.create_index(op.f('ix_citizen_requests_language'), 'citizen_requests', ['language'], unique=False)
    op.create_index(op.f('ix_citizen_requests_region_id'), 'citizen_requests', ['region_id'], unique=False)
    op.create_index(op.f('ix_citizen_requests_status'), 'citizen_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citizen_requests_status'), table_name='citizen_requests')
    op.drop_index(op.f('ix_citizen_requests_region_id'), table_name='citizen_requests')
    op.drop_index(op.f('ix_citizen_requests_language'), table_name='citizen_requests')
    op.drop_index(op.f('ix_citizen_requests_id'), table_name='citizen_requests')
    op.drop_index(op.f('ix_citizen_requests_created_at'), table_name='citizen_requests')
    op.drop_index(op.f('ix_citizen_requests_category'), table_name='citizen_requests')
    op.drop_index(op.f('ix_citizen_requests_anonymous_reference'), table_name='citizen_requests')
    op.drop_table('citizen_requests')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_index(op.f('ix_regions_country_code'), table_name='regions')
    op.drop_index(op.f('ix_regions_code'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
